//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int RestorauntId { get; set; }
        public System.DateTime Time { get; set; }
        public int Persons { get; set; }
    
        public virtual Restoraunt Restoraunt { get; set; }
    }
}
