
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Diplom.ADO
{

using System;
    using System.Collections.Generic;
    
public partial class Restoraunt
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Restoraunt()
    {

        this.Reservation = new HashSet<Reservation>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Adress { get; set; }

    public Nullable<int> Places { get; set; }

    public string Phone { get; set; }

    public Nullable<int> TerraceId { get; set; }

    public string OperatingMode { get; set; }

    public Nullable<int> FoodTypeId { get; set; }

    public Nullable<int> AverageCheckId { get; set; }

    public Nullable<int> AdministratorId { get; set; }

    public byte[] Image { get; set; }



    public virtual AverageCheck AverageCheck { get; set; }

    public virtual FoodType FoodType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reservation> Reservation { get; set; }

    public virtual Terrace Terrace { get; set; }

    public virtual User User { get; set; }

}

}
